---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: my-cluster
  nodes:
    - role: control-plane
      extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: /home/shotler/.docker/config.json
    - role: worker
    - role: worker
    - role: worker
    - role: worker
---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5000
