---
- name: Install multiples pkgs
  become: true
  apt:
    pkg:
    - awscli
    - curl
    - ipcalc
    - jid
    - jq
    - net-tools
    - nmap
    - tilix
    - tree
    - vim
    - virtualbox
    - vlc
    - wireshark
    state: present
    update_cache: yes
