---
- name: Install pre-req
  become: yes
  apt:
    pkg:
    - ansible
    - git

- name: Install roles
  command: "ansible-galaxy install {{ item }}"
  with_items:
    - gantsign.antigen
    - diodonfrost.p10k

- name: Install collections
  command: "ansible-galaxy collection install {{ item }}"
  with_items:
    - community.general
