---
- name: Install requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker ppa
  become: true
  block:
    - name: Download k8s gpg
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o pipefail
          curl -s https://download.docker.com/linux/ubuntu/gpg |
          gpg --dearmor |
          sudo tee /usr/share/keyrings/docker-archive-keyring.gpg >/dev/null
      changed_when: false

    - name: "Add docker ppa"
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ UBUNTU_ARCH.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ UBUNTU_RELEASE.stdout }} stable"
        state: present
        update_cache: true

- name: Install
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Check if dockerd is started
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    group: docker
    append: true
